### ISSUE TITLE
any chance to rescue this error?

### ISSUE THREAD

**Issue by erpe** [mynyml/harmony#11]
irb(main):008:0> p = Harmony::Page.fetch('http://www.ebay.com')
 WARNIING:  [Mon Aug 30 2010 18:18:25 GMT+0200 (CET)] {ENVJS} Exception while loading window: ReferenceError: $w is not defined
Johnson::Error: $w is not defined
    from /usr/local/lib/ruby/gems/1.8/gems/envjs-0.3.7/lib/envjs/static.js:22590 [JavaScript]
    from /usr/local/lib/ruby/gems/1.8/gems/envjs-0.3.7/lib/envjs/static.js:22580 [JavaScript]
    from /usr/local/lib/ruby/gems/1.8/gems/envjs-0.3.7/lib/envjs/static.js:3654 [JavaScript]
    from /usr/local/lib/ruby/gems/1.8/gems/envjs-0.3.7/lib/envjs/env.js:1145 [JavaScript]
    from /usr/local/lib/ruby/gems/1.8/gems/envjs-0.3.7/lib/envjs/env.js:2665 [JavaScript]
    from /usr/local/lib/ruby/gems/1.8/gems/envjs-0.3.7/lib/envjs/env.js:95 [JavaScript]
    from /usr/local/lib/ruby/gems/1.8/gems/envjs-0.3.7/lib/envjs/env.js:2674 [JavaScript]
    from /usr/local/lib/ruby/gems/1.8/gems/envjs-0.3.7/lib/envjs/env.js:6 [JavaScript]
    from /usr/local/lib/ruby/gems/1.8/gems/johnson-2.0.0.pre3/lib/johnson/tracemonkey/runtime.rb:49:in `evaluate_compiled_script'
    from /usr/local/lib/ruby/gems/1.8/gems/envjs-0.3.7/lib/envjs/runtime.rb:53:in`evaluate'
    from /usr/local/lib/ruby/gems/1.8/gems/envjs-0.3.7/lib/envjs/runtime.rb:189:in `extended'
    from /usr/local/lib/ruby/gems/1.8/gems/johnson-2.0.0.pre3/lib/johnson/tracemonkey/js_land_proxy.rb:16:in`call'
    from /usr/local/lib/ruby/gems/1.8/gems/johnson-2.0.0.pre3/lib/johnson/tracemonkey/js_land_proxy.rb:16:in `__send__'
    from /usr/local/lib/ruby/gems/1.8/gems/johnson-2.0.0.pre3/lib/johnson/tracemonkey/js_land_proxy.rb:16:in`send_with_possible_block'
    from /usr/local/lib/ruby/gems/1.8/gems/johnson-2.0.0.pre3/lib/johnson/tracemonkey/runtime.rb:49:in `evaluate_compiled_script_without_clearing_traps'
    from /usr/local/lib/ruby/gems/1.8/gems/envjs-0.3.7/lib/envjs/env.js:596 [JavaScript]
    from /usr/local/lib/ruby/gems/1.8/gems/envjs-0.3.7/lib/envjs/env.js:1116 [JavaScript]
    from none:1 [JavaScript]
    from /usr/local/lib/ruby/gems/1.8/gems/johnson-2.0.0.pre3/lib/johnson/tracemonkey/runtime.rb:49:in`evaluate_compiled_script'
    from /usr/local/lib/ruby/gems/1.8/gems/envjs-0.3.7/lib/envjs/runtime.rb:53:in `evaluate'
    from /usr/local/lib/ruby/gems/1.8/gems/harmony-0.5.6/lib/harmony/page.rb:25:in`from_uri'
    from /usr/local/lib/ruby/gems/1.8/gems/harmony-0.5.6/lib/harmony/page.rb:54:in `fetch'
    from (irb):8irb(main):009:0>

**Comment by briantobin** [comment]
I also experience this problem. Were you able to resolve it?
